-- ============================================================
-- PROYECTO 2 - BASES DE DATOS 2
-- CARGA DIA 1: Simulacion de partidos y resultados
-- Esquema: PROYECTO2BASES2  |  Mundial simulado: 2030
-- IDs ajustados para no chocar con datos existentes
-- ============================================================
-- Ejecutar con F5 en SQL Developer (Run Script)
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET FEEDBACK ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE('============================================================');
    DBMS_OUTPUT.PUT_LINE('INICIO CARGA DIA 1: ' || TO_CHAR(SYSTIMESTAMP, 'DD/MM/YYYY HH24:MI:SS'));
    DBMS_OUTPUT.PUT_LINE('============================================================');
END;
/

-- ------------------------------------------------------------
-- 1. SELECCIONES (IDs desde 200)
-- ------------------------------------------------------------
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (200, 'Argentina 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (201, 'Brasil 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (202, 'Francia 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (203, 'Alemania 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (204, 'España 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (205, 'Inglaterra 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (206, 'Portugal 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (207, 'Italia 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (208, 'Uruguay 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (209, 'Mexico 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (210, 'Estados Unidos 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (211, 'Croacia 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (212, 'Holanda 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (213, 'Morocco 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (214, 'Senegal 2030');
INSERT INTO SELECCION (ID_SELECCION, NOMBRE) VALUES (215, 'Japon 2030');
COMMIT;

-- ------------------------------------------------------------
-- 2. MUNDIAL 2030
-- ------------------------------------------------------------
INSERT INTO MUNDIAL (ANIO, ID_ORGANIZADOR, ORGANIZADOR, ID_CAMPEON, CAMPEON,
                     NUM_SELECCIONES, NUM_PARTIDOS, GOLES, PROMEDIO_GOL)
VALUES (2030, 204, 'España 2030', 200, 'Argentina 2030', 16, 24, 85, 2.66);
COMMIT;

-- ------------------------------------------------------------
-- 3. GRUPOS
-- ------------------------------------------------------------
INSERT INTO GRUPO (ANIO, ID_GRUPO, SELECCIONES) VALUES (2030, 'A', 'Argentina, Brasil, Mexico, Senegal');
INSERT INTO GRUPO (ANIO, ID_GRUPO, SELECCIONES) VALUES (2030, 'B', 'Francia, Alemania, Japon, Morocco');
INSERT INTO GRUPO (ANIO, ID_GRUPO, SELECCIONES) VALUES (2030, 'C', 'España, Inglaterra, Uruguay, Croacia');
INSERT INTO GRUPO (ANIO, ID_GRUPO, SELECCIONES) VALUES (2030, 'D', 'Portugal, Italia, Holanda, Estados Unidos');
COMMIT;

-- ------------------------------------------------------------
-- 4. JUGADORES (IDs desde 9000)
-- ------------------------------------------------------------
-- Argentina
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9001, 'Lautaro Martinez',   200, '1.74', '22/08/1997', 'Argentina');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9002, 'Julian Alvarez',     200, '1.70', '31/01/2000', 'Argentina');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9003, 'Enzo Fernandez',     200, '1.78', '17/01/2001', 'Argentina');
-- Brasil
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9004, 'Vinicius Jr',        201, '1.76', '12/07/2000', 'Brasil');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9005, 'Rodrygo',            201, '1.74', '09/01/2001', 'Brasil');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9006, 'Bruno Guimaraes',    201, '1.83', '16/11/1997', 'Brasil');
-- Francia
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9007, 'Kylian Mbappe',      202, '1.78', '20/12/1998', 'Francia');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9008, 'Antoine Griezmann',  202, '1.76', '21/03/1991', 'Francia');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9009, 'Aurelien Tchouameni',202, '1.87', '16/01/2000', 'Francia');
-- España
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9010, 'Pedri',              204, '1.74', '25/11/2002', 'España');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9011, 'Gavi',               204, '1.73', '05/08/2004', 'España');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9012, 'Ferran Torres',      204, '1.84', '29/02/2000', 'España');
-- Inglaterra
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9013, 'Jude Bellingham',    205, '1.86', '29/06/2003', 'Inglaterra');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9014, 'Harry Kane',         205, '1.88', '28/07/1993', 'Inglaterra');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9015, 'Phil Foden',         205, '1.71', '28/05/2000', 'Inglaterra');
-- Portugal
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9016, 'Rafael Leao',        206, '1.88', '10/06/1999', 'Portugal');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9017, 'Bernardo Silva',     206, '1.73', '10/08/1994', 'Portugal');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9018, 'Ruben Neves',        206, '1.81', '13/03/1997', 'Portugal');
-- Alemania
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9019, 'Florian Wirtz',      203, '1.80', '03/05/2003', 'Alemania');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9020, 'Jamal Musiala',      203, '1.80', '26/02/2003', 'Alemania');
COMMIT;

-- ------------------------------------------------------------
-- 5. PARTIDOS JORNADA 1 (IDs desde 2000)
-- ------------------------------------------------------------
-- Grupo A
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2001, 2030, 1, '10/06/2030', 'Grupo A', 200, 201, 2, 1, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2002, 2030, 2, '10/06/2030', 'Grupo A', 209, 214, 1, 1, 'No', 'No', 0, 0);
-- Grupo B
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2003, 2030, 3, '11/06/2030', 'Grupo B', 202, 203, 3, 0, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2004, 2030, 4, '11/06/2030', 'Grupo B', 215, 213, 0, 2, 'No', 'No', 0, 0);
-- Grupo C
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2005, 2030, 5, '12/06/2030', 'Grupo C', 204, 205, 2, 2, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2006, 2030, 6, '12/06/2030', 'Grupo C', 208, 211, 1, 0, 'No', 'No', 0, 0);
-- Grupo D
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2007, 2030, 7, '13/06/2030', 'Grupo D', 206, 207, 1, 1, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2008, 2030, 8, '13/06/2030', 'Grupo D', 212, 210, 2, 0, 'No', 'No', 0, 0);
COMMIT;

-- ------------------------------------------------------------
-- 6. GOLES (IDs desde 3000)
-- ------------------------------------------------------------
-- Partido 2001: Argentina 2-1 Brasil
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3001, 2001, 200, 9001, 23, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3002, 2001, 200, 9002, 67, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3003, 2001, 201, 9004, 45, 'No', 'No');
-- Partido 2002: Mexico 1-1 Senegal
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3004, 2002, 209, 9001, 55, 'Si', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3005, 2002, 214, 9004, 78, 'No', 'No');
-- Partido 2003: Francia 3-0 Alemania
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3006, 2003, 202, 9007, 12, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3007, 2003, 202, 9007, 44, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3008, 2003, 202, 9008, 88, 'No', 'No');
-- Partido 2004: Japon 0-2 Morocco
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3009, 2004, 213, 9016, 34, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3010, 2004, 213, 9017, 71, 'No', 'No');
-- Partido 2005: España 2-2 Inglaterra
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3011, 2005, 204, 9010, 18, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3012, 2005, 204, 9012, 60, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3013, 2005, 205, 9013, 35, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3014, 2005, 205, 9014, 82, 'Si', 'No');
-- Partido 2006: Uruguay 1-0 Croacia
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3015, 2006, 208, 9002, 57, 'No', 'No');
-- Partido 2007: Portugal 1-1 Italia
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3016, 2007, 206, 9016, 40, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3017, 2007, 207, 9019, 73, 'No', 'No');
-- Partido 2008: Holanda 2-0 Estados Unidos
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3018, 2008, 212, 9020, 29, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3019, 2008, 212, 9019, 65, 'No', 'No');
COMMIT;

-- ------------------------------------------------------------
-- 7. TARJETAS (IDs desde 3000)
-- ------------------------------------------------------------
INSERT INTO TARJETA (ID_TARJETA, ANIO, ID_JUGADOR, ID_SELECCION, AMARILLAS, ROJAS)
VALUES (3001, 2030, 9003, 200, 1, 0);
INSERT INTO TARJETA (ID_TARJETA, ANIO, ID_JUGADOR, ID_SELECCION, AMARILLAS, ROJAS)
VALUES (3002, 2030, 9006, 201, 1, 0);
INSERT INTO TARJETA (ID_TARJETA, ANIO, ID_JUGADOR, ID_SELECCION, AMARILLAS, ROJAS)
VALUES (3003, 2030, 9009, 202, 0, 1);
INSERT INTO TARJETA (ID_TARJETA, ANIO, ID_JUGADOR, ID_SELECCION, AMARILLAS, ROJAS)
VALUES (3004, 2030, 9013, 205, 1, 0);
INSERT INTO TARJETA (ID_TARJETA, ANIO, ID_JUGADOR, ID_SELECCION, AMARILLAS, ROJAS)
VALUES (3005, 2030, 9018, 206, 1, 0);
COMMIT;

-- ------------------------------------------------------------
-- 8. DETALLE JUGADORES
-- ------------------------------------------------------------
INSERT INTO DETALLE_JUGADOR (ID_JUGADOR, ANIO, CAMISETA, POSICION, JUGO, JUGO_TITULAR,
                              CAPITAN, NO_JUGO, GOLES, PROM_GOLES,
                              TARJETA_AMARILLA, TARJETA_ROJA, PG, PE, PP, POS_FINAL)
VALUES (9001, 2030, '9',  'Delantero',      1, 1, 1, 0, 1, 1.00, 0, 0, 1, 0, 0, 0);
INSERT INTO DETALLE_JUGADOR (ID_JUGADOR, ANIO, CAMISETA, POSICION, JUGO, JUGO_TITULAR,
                              CAPITAN, NO_JUGO, GOLES, PROM_GOLES,
                              TARJETA_AMARILLA, TARJETA_ROJA, PG, PE, PP, POS_FINAL)
VALUES (9002, 2030, '9',  'Delantero',      1, 1, 0, 0, 1, 1.00, 0, 0, 1, 0, 0, 0);
INSERT INTO DETALLE_JUGADOR (ID_JUGADOR, ANIO, CAMISETA, POSICION, JUGO, JUGO_TITULAR,
                              CAPITAN, NO_JUGO, GOLES, PROM_GOLES,
                              TARJETA_AMARILLA, TARJETA_ROJA, PG, PE, PP, POS_FINAL)
VALUES (9007, 2030, '10', 'Delantero',      1, 1, 1, 0, 2, 2.00, 0, 0, 1, 0, 0, 0);
INSERT INTO DETALLE_JUGADOR (ID_JUGADOR, ANIO, CAMISETA, POSICION, JUGO, JUGO_TITULAR,
                              CAPITAN, NO_JUGO, GOLES, PROM_GOLES,
                              TARJETA_AMARILLA, TARJETA_ROJA, PG, PE, PP, POS_FINAL)
VALUES (9013, 2030, '5',  'Centrocampista', 1, 1, 0, 0, 1, 1.00, 1, 0, 0, 1, 0, 0);
INSERT INTO DETALLE_JUGADOR (ID_JUGADOR, ANIO, CAMISETA, POSICION, JUGO, JUGO_TITULAR,
                              CAPITAN, NO_JUGO, GOLES, PROM_GOLES,
                              TARJETA_AMARILLA, TARJETA_ROJA, PG, PE, PP, POS_FINAL)
VALUES (9014, 2030, '9',  'Delantero',      1, 1, 1, 0, 1, 1.00, 0, 0, 0, 1, 0, 0);
COMMIT;

-- ------------------------------------------------------------
-- 9. LOGS DIA 1
-- ------------------------------------------------------------
BEGIN
    DBMS_STATS.GATHER_SCHEMA_STATS(
        ownname => 'PROYECTO2BASES2',
        options => 'GATHER',
        estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE
    );
    DBMS_OUTPUT.PUT_LINE('Estadisticas recopiladas.');
END;
/

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM PARTIDO WHERE ANIO = 2030;
    INSERT INTO LOG_PARTIDO (ID_LOG, FECHA_REGISTRO, OPERACION, ANIO_MODIFICADO,
                              CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_PARTIDO.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA1', 2030,
            v_cnt, 0, 'Carga dia 1 - Jornada 1 fase de grupos - ' || v_cnt || ' partidos');

    SELECT COUNT(*) INTO v_cnt FROM GOL WHERE ID_PARTIDO BETWEEN 2001 AND 2008;
    INSERT INTO LOG_GOL (ID_LOG, FECHA_REGISTRO, OPERACION,
                          CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_GOL.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA1',
            v_cnt, 0, 'Carga dia 1 - Goles jornada 1 - ' || v_cnt || ' registros');

    SELECT COUNT(*) INTO v_cnt FROM SELECCION WHERE ID_SELECCION BETWEEN 200 AND 215;
    INSERT INTO LOG_SELECCION (ID_LOG, FECHA_REGISTRO, OPERACION,
                                CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_SELECCION.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA1',
            v_cnt, 0, 'Carga dia 1 - Selecciones Mundial 2030 insertadas');

    SELECT COUNT(*) INTO v_cnt FROM MUNDIAL WHERE ANIO = 2030;
    INSERT INTO LOG_MUNDIAL (ID_LOG, FECHA_REGISTRO, OPERACION, ANIO_MODIFICADO,
                              CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_MUNDIAL.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA1', 2030,
            v_cnt, 0, 'Carga dia 1 - Mundial 2030 creado');

    SELECT COUNT(*) INTO v_cnt FROM JUGADOR_PAIS WHERE ID_JUGADOR BETWEEN 9001 AND 9020;
    INSERT INTO LOG_JUGADOR_PAIS (ID_LOG, FECHA_REGISTRO, OPERACION,
                                   CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_JUGADOR_PAIS.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA1',
            v_cnt, 0, 'Carga dia 1 - Jugadores insertados - ' || v_cnt || ' registros');

    SELECT COUNT(*) INTO v_cnt FROM TARJETA WHERE ANIO = 2030;
    INSERT INTO LOG_TARJETA (ID_LOG, FECHA_REGISTRO, OPERACION,
                              CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_TARJETA.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA1',
            v_cnt, 0, 'Carga dia 1 - Tarjetas jornada 1 - ' || v_cnt || ' registros');

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('LOGs dia 1 registrados.');
END;
/

-- ------------------------------------------------------------
-- VALIDACION FINAL DIA 1 - TODOS LOS DATOS
-- ------------------------------------------------------------
SELECT 'SELECCION'        AS TABLA, COUNT(*) AS TOTAL FROM SELECCION
UNION ALL SELECT 'MUNDIAL'         AS TABLA, COUNT(*) AS TOTAL FROM MUNDIAL
UNION ALL SELECT 'GRUPO'           AS TABLA, COUNT(*) AS TOTAL FROM GRUPO
UNION ALL SELECT 'PARTIDO'         AS TABLA, COUNT(*) AS TOTAL FROM PARTIDO
UNION ALL SELECT 'GOL'             AS TABLA, COUNT(*) AS TOTAL FROM GOL
UNION ALL SELECT 'JUGADOR_PAIS'    AS TABLA, COUNT(*) AS TOTAL FROM JUGADOR_PAIS
UNION ALL SELECT 'DETALLE_JUGADOR' AS TABLA, COUNT(*) AS TOTAL FROM DETALLE_JUGADOR
UNION ALL SELECT 'TARJETA'         AS TABLA, COUNT(*) AS TOTAL FROM TARJETA
UNION ALL SELECT 'POSICION_GRUPO'  AS TABLA, COUNT(*) AS TOTAL FROM POSICION_GRUPO
UNION ALL SELECT 'POSICION_FINAL'  AS TABLA, COUNT(*) AS TOTAL FROM POSICION_FINAL
UNION ALL SELECT 'GOLEADOR'        AS TABLA, COUNT(*) AS TOTAL FROM GOLEADOR
UNION ALL SELECT 'EQUIPO_IDEAL'    AS TABLA, COUNT(*) AS TOTAL FROM EQUIPO_IDEAL
UNION ALL SELECT 'PREMIO'          AS TABLA, COUNT(*) AS TOTAL FROM PREMIO
UNION ALL SELECT 'TIPO_PREMIO'     AS TABLA, COUNT(*) AS TOTAL FROM TIPO_PREMIO
UNION ALL SELECT 'LOG_PARTIDO'     AS TABLA, COUNT(*) AS TOTAL FROM LOG_PARTIDO
UNION ALL SELECT 'LOG_GOL'         AS TABLA, COUNT(*) AS TOTAL FROM LOG_GOL
UNION ALL SELECT 'LOG_SELECCION'   AS TABLA, COUNT(*) AS TOTAL FROM LOG_SELECCION
UNION ALL SELECT 'LOG_TARJETA'     AS TABLA, COUNT(*) AS TOTAL FROM LOG_TARJETA
UNION ALL SELECT 'LOG_MUNDIAL'     AS TABLA, COUNT(*) AS TOTAL FROM LOG_MUNDIAL
UNION ALL SELECT 'LOG_GRUPO'       AS TABLA, COUNT(*) AS TOTAL FROM LOG_GRUPO
UNION ALL SELECT 'LOG_POSICION_GRUPO' AS TABLA, COUNT(*) AS TOTAL FROM LOG_POSICION_GRUPO
UNION ALL SELECT 'LOG_POSICION_FINAL' AS TABLA, COUNT(*) AS TOTAL FROM LOG_POSICION_FINAL
UNION ALL SELECT 'LOG_GOLEADOR'    AS TABLA, COUNT(*) AS TOTAL FROM LOG_GOLEADOR
UNION ALL SELECT 'LOG_EQUIPO_IDEAL' AS TABLA, COUNT(*) AS TOTAL FROM LOG_EQUIPO_IDEAL
UNION ALL SELECT 'LOG_PREMIO'      AS TABLA, COUNT(*) AS TOTAL FROM LOG_PREMIO
UNION ALL SELECT 'LOG_JUGADOR_PAIS' AS TABLA, COUNT(*) AS TOTAL FROM LOG_JUGADOR_PAIS
UNION ALL SELECT 'LOG_DETALLE_JUGADOR' AS TABLA, COUNT(*) AS TOTAL FROM LOG_DETALLE_JUGADOR
UNION ALL SELECT 'LOG_BACKUP'      AS TABLA, COUNT(*) AS TOTAL FROM LOG_BACKUP
ORDER BY TABLA;
