-- ============================================================
-- PROYECTO 2 - BASES DE DATOS 2
-- CARGA DIA 2: Jornada 2 + Cuartos de Final
-- Esquema: PROYECTO2BASES2  |  Mundial simulado: 2030
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET FEEDBACK ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE('============================================================');
    DBMS_OUTPUT.PUT_LINE('INICIO CARGA DIA 2: ' || TO_CHAR(SYSTIMESTAMP, 'DD/MM/YYYY HH24:MI:SS'));
    DBMS_OUTPUT.PUT_LINE('============================================================');
END;
/

-- ------------------------------------------------------------
-- 1. MAS JUGADORES (IDs desde 9021)
-- ------------------------------------------------------------
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9021, 'Federico Valverde', 208, '1.82', '22/07/1998', 'Uruguay');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9022, 'Darwin Nunez',      208, '1.87', '24/06/1999', 'Uruguay');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9023, 'Luka Modric',       211, '1.74', '09/09/1985', 'Croacia');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9024, 'Achraf Hakimi',     213, '1.81', '04/11/1998', 'Morocco');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9025, 'Cody Gakpo',        212, '1.89', '07/05/2000', 'Holanda');
INSERT INTO JUGADOR_PAIS (ID_JUGADOR, NOMBRE, ID_SELECCION, ALTURA, FECHA_NACIMIENTO, NACIONALIDAD)
VALUES (9026, 'Federico Chiesa',   207, '1.75', '25/10/1997', 'Italia');
COMMIT;

-- ------------------------------------------------------------
-- 2. PARTIDOS JORNADA 2 + CUARTOS (IDs desde 2009)
-- ------------------------------------------------------------
-- Grupo A - Jornada 2
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2009, 2030, 9,  '14/06/2030', 'Grupo A', 200, 209, 3, 0, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2010, 2030, 10, '14/06/2030', 'Grupo A', 201, 214, 2, 0, 'No', 'No', 0, 0);
-- Grupo B - Jornada 2
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2011, 2030, 11, '15/06/2030', 'Grupo B', 202, 215, 2, 1, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2012, 2030, 12, '15/06/2030', 'Grupo B', 203, 213, 1, 0, 'No', 'No', 0, 0);
-- Grupo C - Jornada 2
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2013, 2030, 13, '16/06/2030', 'Grupo C', 204, 208, 1, 0, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2014, 2030, 14, '16/06/2030', 'Grupo C', 205, 211, 2, 1, 'No', 'No', 0, 0);
-- Grupo D - Jornada 2
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2015, 2030, 15, '17/06/2030', 'Grupo D', 206, 212, 2, 1, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2016, 2030, 16, '17/06/2030', 'Grupo D', 207, 210, 1, 1, 'No', 'No', 0, 0);
-- Cuartos de Final
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2017, 2030, 17, '24/06/2030', 'Cuartos de Final', 200, 202, 1, 1, 'Si', 'Si', 4, 2);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2018, 2030, 18, '24/06/2030', 'Cuartos de Final', 204, 205, 2, 0, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2019, 2030, 19, '25/06/2030', 'Cuartos de Final', 201, 206, 0, 1, 'No', 'No', 0, 0);
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2020, 2030, 20, '25/06/2030', 'Cuartos de Final', 212, 203, 2, 1, 'No', 'No', 0, 0);
COMMIT;

-- ------------------------------------------------------------
-- 3. GOLES DIA 2 (IDs desde 3020)
-- ------------------------------------------------------------
-- 2009: Argentina 3-0 Mexico
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3020, 2009, 200, 9001, 15, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3021, 2009, 200, 9002, 50, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3022, 2009, 200, 9001, 80, 'Si', 'No');
-- 2010: Brasil 2-0 Senegal
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3023, 2010, 201, 9004, 30, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3024, 2010, 201, 9005, 70, 'No', 'No');
-- 2011: Francia 2-1 Japon
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3025, 2011, 202, 9007, 22, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3026, 2011, 202, 9008, 68, 'No', 'No');
-- 2017: Argentina 1-1 Francia (penales 4-2)
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3027, 2017, 200, 9002, 37, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3028, 2017, 202, 9007, 91, 'No', 'No');
-- 2018: España 2-0 Inglaterra
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3029, 2018, 204, 9011, 44, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3030, 2018, 204, 9010, 78, 'No', 'No');
-- 2019: Brasil 0-1 Portugal
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3031, 2019, 206, 9016, 55, 'No', 'No');
-- 2020: Holanda 2-1 Alemania
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3032, 2020, 212, 9025, 25, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3033, 2020, 212, 9025, 61, 'No', 'No');
INSERT INTO GOL (ID_GOL, ID_PARTIDO, ID_SELECCION, ID_JUGADOR, MINUTO, ES_PENAL, ES_AUTOGOL)
VALUES (3034, 2020, 203, 9020, 72, 'No', 'No');
COMMIT;

-- ------------------------------------------------------------
-- 4. POSICION_GRUPO (IDs desde 600)
-- ------------------------------------------------------------
-- GRUPO A
INSERT INTO POSICION_GRUPO VALUES (600, 2030, 'A', 200, 6, 2, 2, 0, 0, 5, 1,  4, 'SI');
INSERT INTO POSICION_GRUPO VALUES (601, 2030, 'A', 201, 3, 2, 1, 0, 1, 3, 3,  0, 'SI');
INSERT INTO POSICION_GRUPO VALUES (602, 2030, 'A', 209, 1, 2, 0, 1, 1, 1, 4, -3, 'NO');
INSERT INTO POSICION_GRUPO VALUES (603, 2030, 'A', 214, 1, 2, 0, 1, 1, 1, 3, -2, 'NO');
-- GRUPO B
INSERT INTO POSICION_GRUPO VALUES (604, 2030, 'B', 202, 6, 2, 2, 0, 0, 5, 1,  4, 'SI');
INSERT INTO POSICION_GRUPO VALUES (605, 2030, 'B', 203, 3, 2, 1, 0, 1, 1, 3, -2, 'SI');
INSERT INTO POSICION_GRUPO VALUES (606, 2030, 'B', 213, 3, 2, 1, 0, 1, 2, 1,  1, 'NO');
INSERT INTO POSICION_GRUPO VALUES (607, 2030, 'B', 215, 0, 2, 0, 0, 2, 1, 4, -3, 'NO');
-- GRUPO C
INSERT INTO POSICION_GRUPO VALUES (608, 2030, 'C', 204, 4, 2, 1, 1, 0, 3, 2,  1, 'SI');
INSERT INTO POSICION_GRUPO VALUES (609, 2030, 'C', 205, 4, 2, 1, 1, 0, 4, 3,  1, 'SI');
INSERT INTO POSICION_GRUPO VALUES (610, 2030, 'C', 208, 3, 2, 1, 0, 1, 1, 1,  0, 'NO');
INSERT INTO POSICION_GRUPO VALUES (611, 2030, 'C', 211, 0, 2, 0, 0, 2, 1, 3, -2, 'NO');
-- GRUPO D
INSERT INTO POSICION_GRUPO VALUES (612, 2030, 'D', 206, 4, 2, 1, 1, 0, 2, 1,  1, 'SI');
INSERT INTO POSICION_GRUPO VALUES (613, 2030, 'D', 212, 3, 2, 1, 0, 1, 4, 2,  2, 'SI');
INSERT INTO POSICION_GRUPO VALUES (614, 2030, 'D', 207, 1, 2, 0, 1, 1, 2, 2,  0, 'NO');
INSERT INTO POSICION_GRUPO VALUES (615, 2030, 'D', 210, 1, 2, 0, 1, 1, 1, 2, -1, 'NO');
COMMIT;

-- ------------------------------------------------------------
-- 5. TARJETAS DIA 2 (IDs desde 3006)
-- ------------------------------------------------------------
INSERT INTO TARJETA (ID_TARJETA, ANIO, ID_JUGADOR, ID_SELECCION, AMARILLAS, ROJAS)
VALUES (3006, 2030, 9021, 208, 1, 0);
INSERT INTO TARJETA (ID_TARJETA, ANIO, ID_JUGADOR, ID_SELECCION, AMARILLAS, ROJAS)
VALUES (3007, 2030, 9023, 211, 1, 1);
INSERT INTO TARJETA (ID_TARJETA, ANIO, ID_JUGADOR, ID_SELECCION, AMARILLAS, ROJAS)
VALUES (3008, 2030, 9026, 207, 2, 0);
COMMIT;

-- ------------------------------------------------------------
-- 6. GOLEADORES (IDs desde 2000)
-- ------------------------------------------------------------
INSERT INTO GOLEADOR (ID_GOLEADOR, ANIO, ID_SELECCION, ID_JUGADOR, GOLES, PARTIDOS, PROMEDIO)
VALUES (2001, 2030, 200, 9001, 3, 3, 1.00);
INSERT INTO GOLEADOR (ID_GOLEADOR, ANIO, ID_SELECCION, ID_JUGADOR, GOLES, PARTIDOS, PROMEDIO)
VALUES (2002, 2030, 202, 9007, 4, 3, 1.33);
INSERT INTO GOLEADOR (ID_GOLEADOR, ANIO, ID_SELECCION, ID_JUGADOR, GOLES, PARTIDOS, PROMEDIO)
VALUES (2003, 2030, 200, 9002, 2, 3, 0.67);
INSERT INTO GOLEADOR (ID_GOLEADOR, ANIO, ID_SELECCION, ID_JUGADOR, GOLES, PARTIDOS, PROMEDIO)
VALUES (2004, 2030, 201, 9004, 2, 3, 0.67);
INSERT INTO GOLEADOR (ID_GOLEADOR, ANIO, ID_SELECCION, ID_JUGADOR, GOLES, PARTIDOS, PROMEDIO)
VALUES (2005, 2030, 212, 9025, 2, 2, 1.00);
COMMIT;

-- ------------------------------------------------------------
-- 7. LOGS DIA 2
-- ------------------------------------------------------------
BEGIN
    DBMS_STATS.GATHER_SCHEMA_STATS(
        ownname => 'PROYECTO2BASES2',
        options => 'GATHER',
        estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE
    );
END;
/

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM PARTIDO WHERE ANIO = 2030;
    INSERT INTO LOG_PARTIDO (ID_LOG, FECHA_REGISTRO, OPERACION, ANIO_MODIFICADO,
                              CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_PARTIDO.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA2', 2030,
            v_cnt, 0, 'Carga dia 2 - Jornada 2 + Cuartos - ' || v_cnt || ' partidos acumulados');

    SELECT COUNT(*) INTO v_cnt FROM GOL WHERE ID_PARTIDO BETWEEN 2001 AND 2020;
    INSERT INTO LOG_GOL (ID_LOG, FECHA_REGISTRO, OPERACION,
                          CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_GOL.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA2',
            v_cnt, 0, 'Carga dia 2 - Goles acumulados - ' || v_cnt || ' registros');

    SELECT COUNT(*) INTO v_cnt FROM POSICION_GRUPO WHERE ANIO = 2030;
    INSERT INTO LOG_POSICION_GRUPO (ID_LOG, FECHA_REGISTRO, OPERACION,
                                     CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_POSICION_GRUPO.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA2',
            v_cnt, 0, 'Carga dia 2 - Posiciones de grupo finalizadas');

    SELECT COUNT(*) INTO v_cnt FROM GOLEADOR WHERE ANIO = 2030;
    INSERT INTO LOG_GOLEADOR (ID_LOG, FECHA_REGISTRO, OPERACION,
                               CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_GOLEADOR.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA2',
            v_cnt, 0, 'Carga dia 2 - Tabla de goleadores actualizada');

    SELECT COUNT(*) INTO v_cnt FROM TARJETA WHERE ANIO = 2030;
    INSERT INTO LOG_TARJETA (ID_LOG, FECHA_REGISTRO, OPERACION,
                              CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_TARJETA.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA2',
            v_cnt, 0, 'Carga dia 2 - Tarjetas acumuladas - ' || v_cnt || ' registros');

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('LOGs dia 2 registrados.');
END;
/

-- ------------------------------------------------------------
-- VALIDACION DIA 2
-- ------------------------------------------------------------
SELECT 'PARTIDO'           AS TABLA, COUNT(*) AS TOTAL FROM PARTIDO WHERE ANIO = 2030
UNION ALL SELECT 'GOL',              COUNT(*) FROM GOL WHERE ID_PARTIDO BETWEEN 2001 AND 2020
UNION ALL SELECT 'POSICION_GRUPO',   COUNT(*) FROM POSICION_GRUPO WHERE ANIO = 2030
UNION ALL SELECT 'GOLEADOR',         COUNT(*) FROM GOLEADOR WHERE ANIO = 2030
UNION ALL SELECT 'TARJETA',          COUNT(*) FROM TARJETA WHERE ANIO = 2030
UNION ALL SELECT 'JUGADOR_PAIS',     COUNT(*) FROM JUGADOR_PAIS WHERE ID_JUGADOR BETWEEN 9001 AND 9026
UNION ALL SELECT 'LOG_PARTIDO',      COUNT(*) FROM LOG_PARTIDO
UNION ALL SELECT 'LOG_GOL',          COUNT(*) FROM LOG_GOL
UNION ALL SELECT 'LOG_POSICION_GRUPO', COUNT(*) FROM LOG_POSICION_GRUPO
UNION ALL SELECT 'LOG_GOLEADOR',     COUNT(*) FROM LOG_GOLEADOR
UNION ALL SELECT 'LOG_TARJETA',      COUNT(*) FROM LOG_TARJETA;
