-- ============================================================
-- PROYECTO 2 - BASES DE DATOS 2
-- CARGA DIA 3: Semifinales + Final + MAYUSCULAS en paises
-- Esquema: PROYECTO2BASES2  |  Mundial simulado: 2030
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET FEEDBACK ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE('============================================================');
    DBMS_OUTPUT.PUT_LINE('INICIO CARGA DIA 3: ' || TO_CHAR(SYSTIMESTAMP, 'DD/MM/YYYY HH24:MI:SS'));
    DBMS_OUTPUT.PUT_LINE('============================================================');
END;
/

-- ------------------------------------------------------------
-- 1. PARTIDOS SEMIFINALES Y FINAL (IDs desde 2021)
-- ------------------------------------------------------------
INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2021, 2030, 21, '01/07/2030', 'Semifinal', 200, 204, 2, 1, 'No', 'No', 0, 0);

INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2022, 2030, 22, '02/07/2030', 'Semifinal', 206, 212, 1, 1, 'Si', 'Si', 3, 5);

INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2023, 2030, 23, '07/07/2030', 'Tercer Lugar', 204, 206, 3, 2, 'No', 'No', 0, 0);

INSERT INTO PARTIDO (ID_PARTIDO, ANIO, NUM_PARTIDO, FECHA, ETAPA,
                     ID_LOCAL, ID_VISITANTE, GOLES_LOCAL, GOLES_VISITANTE,
                     TIEMPO_EXTRA, PENALES, PENALES_LOCAL, PENALES_VISITANTE)
VALUES (2024, 2030, 24, '09/07/2030', 'Final', 200, 212, 3, 2, 'No', 'No', 0, 0);
COMMIT;

-- ------------------------------------------------------------
-- 2. GOLES FASE FINAL (IDs desde 3035)
-- ------------------------------------------------------------
-- Semifinal ARG 2-1 ESP
INSERT INTO GOL VALUES (3035, 2021, 200, 9001, 28, 'No', 'No');
INSERT INTO GOL VALUES (3036, 2021, 200, 9002, 70, 'No', 'No');
INSERT INTO GOL VALUES (3037, 2021, 204, 9011, 55, 'No', 'No');
-- Semifinal POR 1-1 HOL
INSERT INTO GOL VALUES (3038, 2022, 206, 9016, 40, 'No', 'No');
INSERT INTO GOL VALUES (3039, 2022, 212, 9025, 88, 'No', 'No');
-- Tercer puesto ESP 3-2 POR
INSERT INTO GOL VALUES (3040, 2023, 204, 9012, 20, 'No', 'No');
INSERT INTO GOL VALUES (3041, 2023, 204, 9010, 45, 'No', 'No');
INSERT INTO GOL VALUES (3042, 2023, 204, 9011, 77, 'No', 'No');
INSERT INTO GOL VALUES (3043, 2023, 206, 9017, 35, 'No', 'No');
INSERT INTO GOL VALUES (3044, 2023, 206, 9018, 62, 'No', 'No');
-- FINAL ARG 3-2 HOL
INSERT INTO GOL VALUES (3045, 2024, 200, 9001, 18, 'No', 'No');
INSERT INTO GOL VALUES (3046, 2024, 200, 9002, 52, 'No', 'No');
INSERT INTO GOL VALUES (3047, 2024, 200, 9001, 84, 'Si', 'No');
INSERT INTO GOL VALUES (3048, 2024, 212, 9025, 33, 'No', 'No');
INSERT INTO GOL VALUES (3049, 2024, 212, 9025, 68, 'No', 'No');
COMMIT;

-- ------------------------------------------------------------
-- 3. POSICION FINAL (IDs desde 600)
-- ------------------------------------------------------------
INSERT INTO POSICION_FINAL (ID_POSICION_FINAL, ANIO, POSICION, ID_SELECCION)
VALUES (600, 2030, 1, 200);
INSERT INTO POSICION_FINAL (ID_POSICION_FINAL, ANIO, POSICION, ID_SELECCION)
VALUES (601, 2030, 2, 212);
INSERT INTO POSICION_FINAL (ID_POSICION_FINAL, ANIO, POSICION, ID_SELECCION)
VALUES (602, 2030, 3, 204);
INSERT INTO POSICION_FINAL (ID_POSICION_FINAL, ANIO, POSICION, ID_SELECCION)
VALUES (603, 2030, 4, 206);
COMMIT;

-- ------------------------------------------------------------
-- 4. TIPO_PREMIO (IDs desde 20) y PREMIOS (IDs desde 200)
-- ------------------------------------------------------------
INSERT INTO TIPO_PREMIO (ID_TIPO_PREMIO, NOMBRE) VALUES (20, 'Balon de Oro');
INSERT INTO TIPO_PREMIO (ID_TIPO_PREMIO, NOMBRE) VALUES (21, 'Bota de Oro');
INSERT INTO TIPO_PREMIO (ID_TIPO_PREMIO, NOMBRE) VALUES (22, 'Guante de Oro');
INSERT INTO TIPO_PREMIO (ID_TIPO_PREMIO, NOMBRE) VALUES (23, 'Mejor Jugador Joven');

INSERT INTO PREMIO (ID_PREMIO, ANIO, ID_TIPO_PREMIO, ID_JUGADOR, ID_SELECCION)
VALUES (200, 2030, 20, 9001, 200);
INSERT INTO PREMIO (ID_PREMIO, ANIO, ID_TIPO_PREMIO, ID_JUGADOR, ID_SELECCION)
VALUES (201, 2030, 21, 9001, 200);
INSERT INTO PREMIO (ID_PREMIO, ANIO, ID_TIPO_PREMIO, ID_JUGADOR, ID_SELECCION)
VALUES (202, 2030, 23, 9011, 204);
COMMIT;

-- ------------------------------------------------------------
-- 5. EQUIPO IDEAL (IDs desde 400)
-- ------------------------------------------------------------
INSERT INTO EQUIPO_IDEAL VALUES (400, 2030, 'Portero',        9009, 202);
INSERT INTO EQUIPO_IDEAL VALUES (401, 2030, 'Defensa',        9024, 213);
INSERT INTO EQUIPO_IDEAL VALUES (402, 2030, 'Defensa',        9003, 200);
INSERT INTO EQUIPO_IDEAL VALUES (403, 2030, 'Centrocampista', 9013, 205);
INSERT INTO EQUIPO_IDEAL VALUES (404, 2030, 'Centrocampista', 9010, 204);
INSERT INTO EQUIPO_IDEAL VALUES (405, 2030, 'Centrocampista', 9021, 208);
INSERT INTO EQUIPO_IDEAL VALUES (406, 2030, 'Delantero',      9001, 200);
INSERT INTO EQUIPO_IDEAL VALUES (407, 2030, 'Delantero',      9007, 202);
INSERT INTO EQUIPO_IDEAL VALUES (408, 2030, 'Delantero',      9025, 212);
INSERT INTO EQUIPO_IDEAL VALUES (409, 2030, 'Delantero',      9016, 206);
INSERT INTO EQUIPO_IDEAL VALUES (410, 2030, 'Delantero',      9002, 200);
COMMIT;

-- ------------------------------------------------------------
-- 6. ACTUALIZAR GOLEADORES con totales finales
-- ------------------------------------------------------------
UPDATE GOLEADOR SET GOLES = 5, PARTIDOS = 6, PROMEDIO = 0.83 WHERE ID_GOLEADOR = 2001;
UPDATE GOLEADOR SET GOLES = 4, PARTIDOS = 5, PROMEDIO = 0.80 WHERE ID_GOLEADOR = 2002;
UPDATE GOLEADOR SET GOLES = 4, PARTIDOS = 6, PROMEDIO = 0.67 WHERE ID_GOLEADOR = 2003;
UPDATE GOLEADOR SET GOLES = 2, PARTIDOS = 4, PROMEDIO = 0.50 WHERE ID_GOLEADOR = 2004;
UPDATE GOLEADOR SET GOLES = 4, PARTIDOS = 5, PROMEDIO = 0.80 WHERE ID_GOLEADOR = 2005;
COMMIT;

-- ------------------------------------------------------------
-- 7. CAMBIAR NOMBRES DE PAISES A MAYUSCULAS
--    (solo los del Mundial 2030, IDs 200-215)
-- ------------------------------------------------------------
-- Ver estado ANTES
SELECT ID_SELECCION, NOMBRE AS NOMBRE_ANTES
FROM SELECCION
ORDER BY ID_SELECCION;

-- Actualizar a MAYUSCULAS (TODA LA TABLA)
UPDATE SELECCION
SET NOMBRE = UPPER(NOMBRE);
COMMIT;

-- Ver estado DESPUES
SELECT ID_SELECCION, NOMBRE AS NOMBRE_DESPUES
FROM SELECCION
ORDER BY ID_SELECCION;

-- Registrar en LOG
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM SELECCION;
    INSERT INTO LOG_SELECCION (ID_LOG, FECHA_REGISTRO, OPERACION,
                                CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_SELECCION.NEXTVAL, SYSTIMESTAMP, 'UPDATE_MAYUSCULAS',
            v_cnt, 0, 'Dia 3 - SELECCION COMPLETA convertida a MAYUSCULAS - ' || v_cnt || ' registros afectados');
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('LOG de mayusculas registrado.');
END;
/

-- ------------------------------------------------------------
-- 8. LOGS DIA 3
-- ------------------------------------------------------------
BEGIN
    DBMS_STATS.GATHER_SCHEMA_STATS(
        ownname => 'PROYECTO2BASES2',
        options => 'GATHER',
        estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE
    );
END;
/

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM PARTIDO WHERE ANIO = 2030;
    INSERT INTO LOG_PARTIDO (ID_LOG, FECHA_REGISTRO, OPERACION, ANIO_MODIFICADO,
                              CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_PARTIDO.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA3', 2030,
            v_cnt, 0, 'Carga dia 3 - Semifinales + Final - ' || v_cnt || ' partidos totales');

    SELECT COUNT(*) INTO v_cnt FROM GOL WHERE ID_PARTIDO BETWEEN 2001 AND 2024;
    INSERT INTO LOG_GOL (ID_LOG, FECHA_REGISTRO, OPERACION,
                          CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_GOL.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA3',
            v_cnt, 0, 'Carga dia 3 - Goles totales Mundial 2030 - ' || v_cnt || ' registros');

    SELECT COUNT(*) INTO v_cnt FROM POSICION_FINAL WHERE ANIO = 2030;
    INSERT INTO LOG_POSICION_FINAL (ID_LOG, FECHA_REGISTRO, OPERACION,
                                     CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_POSICION_FINAL.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA3',
            v_cnt, 0, 'Carga dia 3 - Posicion final Mundial 2030 definida');

    SELECT COUNT(*) INTO v_cnt FROM PREMIO WHERE ANIO = 2030;
    INSERT INTO LOG_PREMIO (ID_LOG, FECHA_REGISTRO, OPERACION,
                             CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_PREMIO.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA3',
            v_cnt, 0, 'Carga dia 3 - Premios del Mundial 2030 asignados');

    SELECT COUNT(*) INTO v_cnt FROM EQUIPO_IDEAL WHERE ANIO = 2030;
    INSERT INTO LOG_EQUIPO_IDEAL (ID_LOG, FECHA_REGISTRO, OPERACION,
                                   CANTIDAD_REGISTROS, FRAGMENTACION_PORCENT, DESCRIPCION)
    VALUES (SEQ_LOG_EQUIPO_IDEAL.NEXTVAL, SYSTIMESTAMP, 'CARGA_DIA3',
            v_cnt, 0, 'Carga dia 3 - Equipo ideal del Mundial 2030 registrado');

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('LOGs dia 3 registrados.');
END;
/

-- ------------------------------------------------------------
-- VALIDACION FINAL DIA 3
-- ------------------------------------------------------------
SELECT 'SELECCION'         AS TABLA, COUNT(*) AS TOTAL FROM SELECCION
UNION ALL SELECT 'MUNDIAL',           COUNT(*) FROM MUNDIAL WHERE ANIO = 2030
UNION ALL SELECT 'GRUPO',             COUNT(*) FROM GRUPO WHERE ANIO = 2030
UNION ALL SELECT 'PARTIDO',           COUNT(*) FROM PARTIDO WHERE ANIO = 2030
UNION ALL SELECT 'GOL',               COUNT(*) FROM GOL WHERE ID_PARTIDO BETWEEN 2001 AND 2024
UNION ALL SELECT 'JUGADOR_PAIS',      COUNT(*) FROM JUGADOR_PAIS WHERE ID_JUGADOR BETWEEN 9001 AND 9026
UNION ALL SELECT 'DETALLE_JUGADOR',   COUNT(*) FROM DETALLE_JUGADOR WHERE ANIO = 2030
UNION ALL SELECT 'GOLEADOR',          COUNT(*) FROM GOLEADOR WHERE ANIO = 2030
UNION ALL SELECT 'TARJETA',           COUNT(*) FROM TARJETA WHERE ANIO = 2030
UNION ALL SELECT 'TIPO_PREMIO',       COUNT(*) FROM TIPO_PREMIO WHERE ID_TIPO_PREMIO BETWEEN 20 AND 23
UNION ALL SELECT 'PREMIO',            COUNT(*) FROM PREMIO WHERE ANIO = 2030
UNION ALL SELECT 'EQUIPO_IDEAL',      COUNT(*) FROM EQUIPO_IDEAL WHERE ANIO = 2030
UNION ALL SELECT 'POSICION_GRUPO',    COUNT(*) FROM POSICION_GRUPO WHERE ANIO = 2030
UNION ALL SELECT 'POSICION_FINAL',    COUNT(*) FROM POSICION_FINAL WHERE ANIO = 2030;

SELECT 'LOG_SELECCION'     AS LOG_TABLA, COUNT(*) AS ENTRADAS FROM LOG_SELECCION
UNION ALL SELECT 'LOG_MUNDIAL',           COUNT(*) FROM LOG_MUNDIAL
UNION ALL SELECT 'LOG_PARTIDO',           COUNT(*) FROM LOG_PARTIDO
UNION ALL SELECT 'LOG_GOL',               COUNT(*) FROM LOG_GOL
UNION ALL SELECT 'LOG_GOLEADOR',          COUNT(*) FROM LOG_GOLEADOR
UNION ALL SELECT 'LOG_TARJETA',           COUNT(*) FROM LOG_TARJETA
UNION ALL SELECT 'LOG_POSICION_GRUPO',    COUNT(*) FROM LOG_POSICION_GRUPO
UNION ALL SELECT 'LOG_POSICION_FINAL',    COUNT(*) FROM LOG_POSICION_FINAL
UNION ALL SELECT 'LOG_PREMIO',            COUNT(*) FROM LOG_PREMIO
UNION ALL SELECT 'LOG_EQUIPO_IDEAL',      COUNT(*) FROM LOG_EQUIPO_IDEAL
UNION ALL SELECT 'LOG_JUGADOR_PAIS',      COUNT(*) FROM LOG_JUGADOR_PAIS
UNION ALL SELECT 'LOG_DETALLE_JUGADOR',   COUNT(*) FROM LOG_DETALLE_JUGADOR;

BEGIN
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('=== FIN CARGA DIA 3 - CARGA COMPLETA ===');
    DBMS_OUTPUT.PUT_LINE('Tomar captura con fecha/hora visible del SO.');
    DBMS_OUTPUT.PUT_LINE('SIGUIENTE PASO: Ejecutar backup FULL y DIFERENCIAL.');
END;
/
