-- ========================================================
-- SCRIPT DDL PARA RECREAR ESTRUCTURA DE BASE DE DATOS
-- Proyecto: PROYECTO2BASES2 (Mundial de Fútbol)
-- Fecha: jueves-abril-09-2026
-- 
-- PROPÓSITO: Elimina objetos existentes y recreacrea la 
-- estructura completa incluyendo tablas, secuencias y
-- constraints (claves primarias y extranjeras)
-- ========================================================

-- FASE 1: ELIMINAR OBJETOS EXISTENTES
-- Limpia secuencias (sequences) de auditoría
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_DETALLE_JUGADOR";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_EQUIPO_IDEAL";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_GOL";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_GOLEADOR";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_GRUPO";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_JUGADOR_PAIS";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_MUNDIAL";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_PARTIDO";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_POSICION_FINAL";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_POSICION_GRUPO";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_PREMIO";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_SELECCION";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_TARJETA";
DROP SEQUENCE "PROYECTO2BASES2"."SEQ_LOG_TIPO_PREMIO";

-- Elimina tablas de datos e intermediasilma tablas de auditoría (LOG_*) con cascade
-- para eliminar también sus dependencias (constraints, índices)
DROP TABLE "PROYECTO2BASES2"."DETALLE_JUGADOR" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."GOL" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."GOLEADOR" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."GRUPO" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."JUGADOR_PAIS" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_DETALLE_JUGADOR" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_EQUIPO_IDEAL" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_GOL" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_GOLEADOR" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_GRUPO" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_JUGADOR_PAIS" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_MUNDIAL" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_PARTIDO" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_POSICION_FINAL" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_POSICION_GRUPO" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_PREMIO" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_SELECCION" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_TARJETA" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."LOG_TIPO_PREMIO" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."MUNDIAL" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."PARTIDO" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."POSICION_FINAL" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."POSICION_GRUPO" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."PREMIO" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."SELECCION" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."TARJETA" cascade constraints;
DROP TABLE "PROYECTO2BASES2"."TIPO_PREMIO" cascade constraints;

-- Elimina procedimientos almacenados
DROP PROCEDURE "PROYECTO2BASES2"."SP_INFO_MUNDIAL";
DROP PROCEDURE "PROYECTO2BASES2"."SP_INFO_PAIS";
-- ========================================================
-- FASE 2: CREAR SECUENCIAS PARA AUTOINCREMENTABLES
-- Se usan para generar IDs únicos en las tablas de LOG
-- ========================================================
--  DDL for Sequence SEQ_LOG_DETALLE_JUGADOR
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_DETALLE_JUGADOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10792 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_EQUIPO_IDEAL
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_EQUIPO_IDEAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 255 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_GOL
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_GOL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2725 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_GOLEADOR
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_GOLEADOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1644 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_GRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_GRUPO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 126 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_JUGADOR_PAIS
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_JUGADOR_PAIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8392 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_MUNDIAL
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_MUNDIAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_PARTIDO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_PARTIDO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1695 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_POSICION_FINAL
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_POSICION_FINAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 491 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_POSICION_GRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_POSICION_GRUPO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 491 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_PREMIO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_PREMIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 105 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_SELECCION
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_SELECCION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 92 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_TARJETA
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_TARJETA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2184 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOG_TIPO_PREMIO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO2BASES2"."SEQ_LOG_TIPO_PREMIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 12 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table DETALLE_JUGADOR
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."DETALLE_JUGADOR" 
   (	"ID_JUGADOR" NUMBER, 
	"ANIO" NUMBER(4,0), 
	"CAMISETA" VARCHAR2(20 BYTE), 
	"POSICION" VARCHAR2(50 BYTE), 
	"JUGO" NUMBER, 
	"JUGO_TITULAR" NUMBER, 
	"CAPITAN" NUMBER, 
	"NO_JUGO" NUMBER, 
	"GOLES" NUMBER, 
	"PROM_GOLES" NUMBER(5,2), 
	"TARJETA_AMARILLA" NUMBER, 
	"TARJETA_ROJA" NUMBER, 
	"PG" NUMBER, 
	"PE" NUMBER, 
	"PP" NUMBER, 
	"POS_FINAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

-- ========================================================
-- FASE 3: CREAR TABLAS DE DATOS
-- ========================================================
-- Estructura de cada CREATE TABLE:
--   - Columnas con tipos de datos (NUMBER, VARCHAR2, TIMESTAMP)
--   - SEGMENT CREATION IMMEDIATE: Espacio reservado inmediatamente
--   - PCTFREE/PCTUSED: Espacio libre/usado para updates
--   - STORAGE: Parámetros de almacenamiento físico
--   - TABLESPACE: Ubicación de almacenamiento en disco

--------------------------------------------------------
--  DDL for Table EQUIPO_IDEAL
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" 
   (	"ID_EQUIPO_IDEAL" NUMBER, 
	"ANIO" NUMBER(4,0), 
	"POSICION" VARCHAR2(50 BYTE), 
	"ID_JUGADOR" NUMBER, 
	"ID_SELECCION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOL
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."GOL" 
   (	"ID_GOL" NUMBER, 
	"ID_PARTIDO" NUMBER, 
	"ID_SELECCION" NUMBER, 
	"ID_JUGADOR" NUMBER, 
	"MINUTO" NUMBER, 
	"ES_PENAL" VARCHAR2(2 BYTE), 
	"ES_AUTOGOL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOLEADOR
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."GOLEADOR" 
   (	"ID_GOLEADOR" NUMBER, 
	"ANIO" NUMBER(4,0), 
	"ID_SELECCION" NUMBER, 
	"ID_JUGADOR" NUMBER, 
	"GOLES" NUMBER, 
	"PARTIDOS" NUMBER, 
	"PROMEDIO" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRUPO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."GRUPO" 
   (	"ANIO" NUMBER(4,0), 
	"ID_GRUPO" VARCHAR2(5 BYTE), 
	"SELECCIONES" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JUGADOR_PAIS
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."JUGADOR_PAIS" 
   (	"ID_JUGADOR" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"ID_SELECCION" NUMBER, 
	"ALTURA" VARCHAR2(20 BYTE), 
	"FECHA_NACIMIENTO" VARCHAR2(30 BYTE), 
	"NACIONALIDAD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_DETALLE_JUGADOR
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_DETALLE_JUGADOR" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_EQUIPO_IDEAL
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_EQUIPO_IDEAL" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_GOL
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_GOL" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_GOLEADOR
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_GOLEADOR" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_GRUPO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_GRUPO" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_JUGADOR_PAIS
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_JUGADOR_PAIS" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_MUNDIAL
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_MUNDIAL" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"ANIO_MODIFICADO" NUMBER(4,0), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_PARTIDO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_PARTIDO" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"ANIO_MODIFICADO" NUMBER(4,0), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_POSICION_FINAL
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_POSICION_FINAL" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_POSICION_GRUPO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_POSICION_GRUPO" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_PREMIO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_PREMIO" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_SELECCION
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_SELECCION" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_TARJETA
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_TARJETA" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_TIPO_PREMIO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."LOG_TIPO_PREMIO" 
   (	"ID_LOG" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"OPERACION" VARCHAR2(50 BYTE), 
	"CANTIDAD_REGISTROS" NUMBER, 
	"FRAGMENTACION_PORCENT" NUMBER(5,2), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUNDIAL
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."MUNDIAL" 
   (	"ANIO" NUMBER(4,0), 
	"ID_ORGANIZADOR" NUMBER, 
	"ORGANIZADOR" VARCHAR2(100 BYTE), 
	"ID_CAMPEON" NUMBER, 
	"CAMPEON" VARCHAR2(100 BYTE), 
	"NUM_SELECCIONES" NUMBER, 
	"NUM_PARTIDOS" NUMBER, 
	"GOLES" NUMBER, 
	"PROMEDIO_GOL" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARTIDO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."PARTIDO" 
   (	"ID_PARTIDO" NUMBER, 
	"ANIO" NUMBER(4,0), 
	"NUM_PARTIDO" NUMBER, 
	"FECHA" VARCHAR2(20 BYTE), 
	"ETAPA" VARCHAR2(100 BYTE), 
	"ID_LOCAL" NUMBER, 
	"ID_VISITANTE" NUMBER, 
	"GOLES_LOCAL" NUMBER, 
	"GOLES_VISITANTE" NUMBER, 
	"TIEMPO_EXTRA" VARCHAR2(2 BYTE), 
	"PENALES" VARCHAR2(2 BYTE), 
	"PENALES_LOCAL" NUMBER, 
	"PENALES_VISITANTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSICION_FINAL
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."POSICION_FINAL" 
   (	"ID_POSICION_FINAL" NUMBER, 
	"ANIO" NUMBER(4,0), 
	"POSICION" NUMBER, 
	"ID_SELECCION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSICION_GRUPO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."POSICION_GRUPO" 
   (	"ID_POSICION_GRUPO" NUMBER, 
	"ANIO" NUMBER(4,0), 
	"ID_GRUPO" VARCHAR2(5 BYTE), 
	"ID_SELECCION" NUMBER, 
	"PTS" NUMBER, 
	"PJ" NUMBER, 
	"PG" NUMBER, 
	"PE" NUMBER, 
	"PP" NUMBER, 
	"GF" NUMBER, 
	"GC" NUMBER, 
	"DIFERENCIA" NUMBER, 
	"CLASIFICADO" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREMIO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."PREMIO" 
   (	"ID_PREMIO" NUMBER, 
	"ANIO" NUMBER(4,0), 
	"ID_TIPO_PREMIO" NUMBER, 
	"ID_JUGADOR" NUMBER, 
	"ID_SELECCION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SELECCION
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."SELECCION" 
   (	"ID_SELECCION" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TARJETA
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."TARJETA" 
   (	"ID_TARJETA" NUMBER, 
	"ANIO" NUMBER(4,0), 
	"ID_JUGADOR" NUMBER, 
	"ID_SELECCION" NUMBER, 
	"AMARILLAS" NUMBER DEFAULT 0, 
	"ROJAS" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_PREMIO
--------------------------------------------------------

  CREATE TABLE "PROYECTO2BASES2"."TIPO_PREMIO" 
   (	"ID_TIPO_PREMIO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MUNDIAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_MUNDIAL" ON "PROYECTO2BASES2"."MUNDIAL" ("ANIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_JUGADOR_PAIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_JUGADOR_PAIS" ON "PROYECTO2BASES2"."JUGADOR_PAIS" ("ID_JUGADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_PARTIDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."UQ_PARTIDO" ON "PROYECTO2BASES2"."PARTIDO" ("ANIO", "NUM_PARTIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_TARJETA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."UQ_TARJETA" ON "PROYECTO2BASES2"."TARJETA" ("ANIO", "ID_JUGADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_PREMIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."UQ_PREMIO" ON "PROYECTO2BASES2"."PREMIO" ("ANIO", "ID_TIPO_PREMIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_EQIDEAL_JUG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."UQ_EQIDEAL_JUG" ON "PROYECTO2BASES2"."EQUIPO_IDEAL" ("ANIO", "ID_JUGADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GOLEADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_GOLEADOR" ON "PROYECTO2BASES2"."GOLEADOR" ("ID_GOLEADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_POSFIN_POSICION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."UQ_POSFIN_POSICION" ON "PROYECTO2BASES2"."POSICION_FINAL" ("ANIO", "POSICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_POSFIN_SELECCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."UQ_POSFIN_SELECCION" ON "PROYECTO2BASES2"."POSICION_FINAL" ("ANIO", "ID_SELECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SELECCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_SELECCION" ON "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_POSICION_FINAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_POSICION_FINAL" ON "PROYECTO2BASES2"."POSICION_FINAL" ("ID_POSICION_FINAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DETALLE_JUGADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_DETALLE_JUGADOR" ON "PROYECTO2BASES2"."DETALLE_JUGADOR" ("ID_JUGADOR", "ANIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EQUIPO_IDEAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_EQUIPO_IDEAL" ON "PROYECTO2BASES2"."EQUIPO_IDEAL" ("ID_EQUIPO_IDEAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_POSICION_GRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_POSICION_GRUPO" ON "PROYECTO2BASES2"."POSICION_GRUPO" ("ID_POSICION_GRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_POSICION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."UQ_POSICION" ON "PROYECTO2BASES2"."POSICION_GRUPO" ("ANIO", "ID_GRUPO", "ID_SELECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_TIPO_PREMIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."UQ_TIPO_PREMIO" ON "PROYECTO2BASES2"."TIPO_PREMIO" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PREMIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_PREMIO" ON "PROYECTO2BASES2"."PREMIO" ("ID_PREMIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIPO_PREMIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_TIPO_PREMIO" ON "PROYECTO2BASES2"."TIPO_PREMIO" ("ID_TIPO_PREMIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PARTIDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_PARTIDO" ON "PROYECTO2BASES2"."PARTIDO" ("ID_PARTIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TARJETA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_TARJETA" ON "PROYECTO2BASES2"."TARJETA" ("ID_TARJETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_GRUPO" ON "PROYECTO2BASES2"."GRUPO" ("ANIO", "ID_GRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GOL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO2BASES2"."PK_GOL" ON "PROYECTO2BASES2"."GOL" ("ID_GOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_JUGADOR_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_DETALLE_JUGADOR_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."DETALLE_JUGADOR"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_DETALLE_JUGADOR" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_DETALLE_JUGADOR.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de detalle'
    );
END TRG_DETALLE_JUGADOR_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_DETALLE_JUGADOR_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EQUIPO_IDEAL_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_EQUIPO_IDEAL_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."EQUIPO_IDEAL"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_EQUIPO_IDEAL" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_EQUIPO_IDEAL.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de equipo ideal'
    );
END TRG_EQUIPO_IDEAL_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_EQUIPO_IDEAL_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_GOLEADOR_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_GOLEADOR_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."GOLEADOR"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_GOLEADOR" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_GOLEADOR.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de goleador'
    );
END TRG_GOLEADOR_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_GOLEADOR_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_GOL_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_GOL_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."GOL"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_GOL" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_GOL.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de gol'
    );
END TRG_GOL_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_GOL_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_GRUPO_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_GRUPO_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."GRUPO"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_GRUPO" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_GRUPO.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de grupo'
    );
END TRG_GRUPO_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_GRUPO_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_JUGADOR_PAIS_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_JUGADOR_PAIS_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."JUGADOR_PAIS"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_JUGADOR_PAIS" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_JUGADOR_PAIS.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de jugador'
    );
END TRG_JUGADOR_PAIS_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_JUGADOR_PAIS_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MUNDIAL_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_MUNDIAL_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."MUNDIAL"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_MUNDIAL" (
        ID_LOG, FECHA_REGISTRO, OPERACION, ANIO_MODIFICADO, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_MUNDIAL.NEXTVAL, SYSTIMESTAMP, 'INSERT', :NEW.ANIO, 1, 'Inserción de registro'
    );
END TRG_MUNDIAL_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_MUNDIAL_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PARTIDO_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_PARTIDO_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."PARTIDO"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_PARTIDO" (
        ID_LOG, FECHA_REGISTRO, OPERACION, ANIO_MODIFICADO, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_PARTIDO.NEXTVAL, SYSTIMESTAMP, 'INSERT', :NEW.ANIO, 1, 'Inserción de registro'
    );
END TRG_PARTIDO_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_PARTIDO_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_POSICION_FINAL_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_POSICION_FINAL_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."POSICION_FINAL"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_POSICION_FINAL" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_POSICION_FINAL.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de posición final'
    );
END TRG_POSICION_FINAL_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_POSICION_FINAL_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_POSICION_GRUPO_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_POSICION_GRUPO_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."POSICION_GRUPO"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_POSICION_GRUPO" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_POSICION_GRUPO.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de posición grupo'
    );
END TRG_POSICION_GRUPO_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_POSICION_GRUPO_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PREMIO_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_PREMIO_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."PREMIO"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_PREMIO" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_PREMIO.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de premio'
    );
END TRG_PREMIO_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_PREMIO_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SELECCION_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_SELECCION_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."SELECCION"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_SELECCION" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_SELECCION.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de país'
    );
END TRG_SELECCION_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_SELECCION_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TARJETA_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_TARJETA_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."TARJETA"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_TARJETA" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_TARJETA.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de tarjeta'
    );
END TRG_TARJETA_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_TARJETA_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TIPO_PREMIO_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO2BASES2"."TRG_TIPO_PREMIO_INSERT" 
AFTER INSERT ON "PROYECTO2BASES2"."TIPO_PREMIO"
FOR EACH ROW
BEGIN
    INSERT INTO "PROYECTO2BASES2"."LOG_TIPO_PREMIO" (
        ID_LOG, FECHA_REGISTRO, OPERACION, CANTIDAD_REGISTROS, DESCRIPCION
    )
    VALUES (
        "PROYECTO2BASES2".SEQ_LOG_TIPO_PREMIO.NEXTVAL, SYSTIMESTAMP, 'INSERT', 1, 'Inserción de tipo premio'
    );
END TRG_TIPO_PREMIO_INSERT;

/
ALTER TRIGGER "PROYECTO2BASES2"."TRG_TIPO_PREMIO_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Procedure SP_INFO_MUNDIAL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO2BASES2"."SP_INFO_MUNDIAL" (
    p_anio          IN NUMBER,
    p_id_grupo      IN VARCHAR2 DEFAULT NULL,
    p_id_seleccion  IN NUMBER DEFAULT NULL,
    p_etapa         IN VARCHAR2 DEFAULT NULL
)
AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM MUNDIAL WHERE ANIO = p_anio;
    IF v_count = 0 THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: Año ' || p_anio || ' no encontrado.');
        RETURN;
    END IF;

    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════════════════════');
    DBMS_OUTPUT.PUT_LINE('MUNDIAL ' || p_anio);
    DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════════════════════');

    FOR rec IN (
        SELECT
            s_org.NOMBRE AS ORGANIZADOR,
            s_cam.NOMBRE AS CAMPEON,
            m.NUM_SELECCIONES,
            m.NUM_PARTIDOS,
            m.GOLES,
            m.PROMEDIO_GOL
        FROM MUNDIAL m
        LEFT JOIN SELECCION s_org ON m.ID_ORGANIZADOR = s_org.ID_SELECCION
        LEFT JOIN SELECCION s_cam ON m.ID_CAMPEON = s_cam.ID_SELECCION
        WHERE m.ANIO = p_anio
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('Organizador: ' || rec.ORGANIZADOR);
        DBMS_OUTPUT.PUT_LINE('Campeón: '     || rec.CAMPEON);
        DBMS_OUTPUT.PUT_LINE('Selecciones: ' || rec.NUM_SELECCIONES);
        DBMS_OUTPUT.PUT_LINE('Partidos: '    || rec.NUM_PARTIDOS);
        DBMS_OUTPUT.PUT_LINE('Goles totales: '|| rec.GOLES);
        DBMS_OUTPUT.PUT_LINE('Promedio goles por partido: ' || rec.PROMEDIO_GOL);
    END LOOP;

    -- ========== GRUPOS ==========
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');
    DBMS_OUTPUT.PUT_LINE('GRUPOS');
    DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');

    FOR rec_grupo IN (
        SELECT DISTINCT ID_GRUPO, SELECCIONES
        FROM GRUPO
        WHERE ANIO = p_anio
        AND (p_id_grupo IS NULL OR ID_GRUPO = p_id_grupo)
        ORDER BY ID_GRUPO
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('GRUPO ' || rec_grupo.ID_GRUPO || ': ' || rec_grupo.SELECCIONES);

        FOR rec_pos IN (
            SELECT
                s.NOMBRE,
                pg.PJ, pg.PG, pg.PE, pg.PP,
                pg.GF, pg.GC, pg.DIFERENCIA, pg.PTS,
                DECODE(pg.CLASIFICADO, 'SI', 'Clasificado', 'NO', 'Eliminado', pg.CLASIFICADO) AS CLASIFICADO
            FROM POSICION_GRUPO pg
            JOIN SELECCION s ON pg.ID_SELECCION = s.ID_SELECCION
            WHERE pg.ANIO = p_anio
            AND pg.ID_GRUPO = rec_grupo.ID_GRUPO
            AND (p_id_seleccion IS NULL OR pg.ID_SELECCION = p_id_seleccion)
            ORDER BY pg.PTS DESC, pg.DIFERENCIA DESC
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('  ' || RPAD(rec_pos.NOMBRE, 25) ||
                ' PJ:' || rec_pos.PJ ||
                ' PG:' || rec_pos.PG ||
                ' PE:' || rec_pos.PE ||
                ' PP:' || rec_pos.PP ||
                ' GF:' || rec_pos.GF ||
                ' GC:' || rec_pos.GC ||
                ' DIF:' || rec_pos.DIFERENCIA ||
                ' PTS:' || rec_pos.PTS ||
                ' ' || rec_pos.CLASIFICADO);
        END LOOP;
    END LOOP;

    -- ========== PARTIDOS ==========
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');
    DBMS_OUTPUT.PUT_LINE('PARTIDOS');
    DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');

    FOR rec_partido IN (
        SELECT
            p.FECHA,
            p.ETAPA,
            s_local.NOMBRE AS LOCAL,
            s_visit.NOMBRE AS VISITANTE,
            p.GOLES_LOCAL,
            p.GOLES_VISITANTE,
            DECODE(p.PENALES, 'Si', ' (' || p.PENALES_LOCAL || '-' || p.PENALES_VISITANTE || ' pen)', '') AS PENALES_STR
        FROM PARTIDO p
        LEFT JOIN SELECCION s_local ON p.ID_LOCAL  = s_local.ID_SELECCION
        LEFT JOIN SELECCION s_visit ON p.ID_VISITANTE = s_visit.ID_SELECCION
        WHERE p.ANIO = p_anio
        AND (p_id_grupo IS NULL OR
             p.ID_LOCAL IN (SELECT ID_SELECCION FROM POSICION_GRUPO
                            WHERE ANIO = p_anio AND ID_GRUPO = p_id_grupo)
             OR
             p.ID_VISITANTE IN (SELECT ID_SELECCION FROM POSICION_GRUPO
                                WHERE ANIO = p_anio AND ID_GRUPO = p_id_grupo))
        AND (p_id_seleccion IS NULL OR p.ID_LOCAL = p_id_seleccion OR p.ID_VISITANTE = p_id_seleccion)
        AND (p_etapa IS NULL OR p.ETAPA = p_etapa)
        ORDER BY p.FECHA, p.NUM_PARTIDO
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            RPAD(rec_partido.LOCAL, 22) || ' ' ||
            rec_partido.GOLES_LOCAL || '-' || rec_partido.GOLES_VISITANTE || ' ' ||
            RPAD(rec_partido.VISITANTE, 22) ||
            '  [' || rec_partido.FECHA || ' | ' || rec_partido.ETAPA || ']' ||
            rec_partido.PENALES_STR
        );
    END LOOP;

    -- ========== TOP GOLEADORES ==========
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');
    DBMS_OUTPUT.PUT_LINE('TOP GOLEADORES');
    DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');

    FOR rec_gol IN (
        SELECT
            jp.NOMBRE AS JUGADOR,
            s.NOMBRE  AS SELECCION,
            g.GOLES,
            g.PARTIDOS,
            g.PROMEDIO
        FROM GOLEADOR g
        JOIN JUGADOR_PAIS jp ON g.ID_JUGADOR    = jp.ID_JUGADOR
        JOIN SELECCION    s  ON g.ID_SELECCION  = s.ID_SELECCION
        WHERE g.ANIO = p_anio
        AND (p_id_seleccion IS NULL OR g.ID_SELECCION = p_id_seleccion)
        ORDER BY g.GOLES DESC, g.PROMEDIO DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('  ' || RPAD(rec_gol.JUGADOR, 25) ||
            ' (' || rec_gol.SELECCION || ') - ' ||
            rec_gol.GOLES || ' goles en ' || rec_gol.PARTIDOS || ' partidos');
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════════════════════');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END sp_info_mundial;


/
--------------------------------------------------------
--  DDL for Procedure SP_INFO_PAIS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO2BASES2"."SP_INFO_PAIS" (
    p_id_seleccion     IN NUMBER,
    p_anio             IN NUMBER   DEFAULT NULL,
    p_mostrar_detalles IN VARCHAR2 DEFAULT 'S'
)
AS
    v_nombre_pais VARCHAR2(100);
    v_count       NUMBER;
BEGIN
    SELECT NOMBRE INTO v_nombre_pais
    FROM SELECCION WHERE ID_SELECCION = p_id_seleccion;

    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════════════════════');
    DBMS_OUTPUT.PUT_LINE('INFORMACIÓN DE ' || UPPER(v_nombre_pais));
    DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════════════════════');

    -- ========== AÑOS DE PARTICIPACIÓN ==========
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('AÑOS DE PARTICIPACIÓN:');
    DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');

    FOR rec_anio IN (
        SELECT DISTINCT pg.ANIO, pf.POSICION
        FROM POSICION_GRUPO pg
        LEFT JOIN POSICION_FINAL pf
            ON pg.ANIO = pf.ANIO AND pg.ID_SELECCION = pf.ID_SELECCION
        WHERE pg.ID_SELECCION = p_id_seleccion
        AND (p_anio IS NULL OR pg.ANIO = p_anio)
        ORDER BY pg.ANIO DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('  ' || rec_anio.ANIO ||
            CASE WHEN rec_anio.POSICION = 1 THEN '  CAMPEÓN'
                 WHEN rec_anio.POSICION = 2 THEN '  Subcampeón'
                 WHEN rec_anio.POSICION <= 4 THEN '  Semifinalista'
                 ELSE '  (Posición: ' || rec_anio.POSICION || ')'
            END);
    END LOOP;

    -- ========== SEDE ==========
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('SEDE DE MUNDIALES:');
    DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');

    SELECT COUNT(*) INTO v_count FROM MUNDIAL WHERE ID_ORGANIZADOR = p_id_seleccion;

    IF v_count > 0 THEN
        FOR rec_sede IN (
            SELECT ANIO FROM MUNDIAL WHERE ID_ORGANIZADOR = p_id_seleccion ORDER BY ANIO
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('  Organizador en ' || rec_sede.ANIO);
        END LOOP;
    ELSE
        DBMS_OUTPUT.PUT_LINE('  No ha sido sede');
    END IF;

    -- ========== DESEMPEÑO POR MUNDIAL ==========
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('DESEMPEÑO POR MUNDIAL:');
    DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');

    FOR rec_desem IN (
        SELECT
            m.ANIO,
            COUNT(CASE WHEN (p.ID_LOCAL = p_id_seleccion OR p.ID_VISITANTE = p_id_seleccion) THEN 1 END) AS PARTIDOS,
            SUM(CASE WHEN (p.ID_LOCAL = p_id_seleccion AND p.GOLES_LOCAL > p.GOLES_VISITANTE)
                     OR   (p.ID_VISITANTE = p_id_seleccion AND p.GOLES_VISITANTE > p.GOLES_LOCAL)
                     THEN 1 ELSE 0 END) AS GANADOS,
            SUM(CASE WHEN (p.ID_LOCAL = p_id_seleccion AND p.GOLES_LOCAL = p.GOLES_VISITANTE)
                     OR   (p.ID_VISITANTE = p_id_seleccion AND p.GOLES_VISITANTE = p.GOLES_LOCAL)
                     THEN 1 ELSE 0 END) AS EMPATADOS,
            SUM(CASE WHEN (p.ID_LOCAL = p_id_seleccion AND p.GOLES_LOCAL < p.GOLES_VISITANTE)
                     OR   (p.ID_VISITANTE = p_id_seleccion AND p.GOLES_VISITANTE < p.GOLES_LOCAL)
                     THEN 1 ELSE 0 END) AS PERDIDOS,
            SUM(CASE WHEN p.ID_LOCAL     = p_id_seleccion THEN p.GOLES_LOCAL
                     WHEN p.ID_VISITANTE = p_id_seleccion THEN p.GOLES_VISITANTE
                     ELSE 0 END) AS GOLES,
            SUM(CASE WHEN p.ID_LOCAL     = p_id_seleccion THEN p.GOLES_VISITANTE
                     WHEN p.ID_VISITANTE = p_id_seleccion THEN p.GOLES_LOCAL
                     ELSE 0 END) AS GOLES_CONTRA
        FROM MUNDIAL m
        LEFT JOIN PARTIDO p ON m.ANIO = p.ANIO
        WHERE (p.ID_LOCAL = p_id_seleccion OR p.ID_VISITANTE = p_id_seleccion OR p.ANIO IS NULL)
        AND (p_anio IS NULL OR m.ANIO = p_anio)
        GROUP BY m.ANIO
        ORDER BY m.ANIO DESC
    ) LOOP
        IF rec_desem.PARTIDOS > 0 THEN
            DBMS_OUTPUT.PUT_LINE('  ' || rec_desem.ANIO || ': ' ||
                rec_desem.PARTIDOS || 'PJ | ' ||
                rec_desem.GANADOS  || 'G '    ||
                rec_desem.EMPATADOS|| 'E '    ||
                rec_desem.PERDIDOS || 'P | '  ||
                rec_desem.GOLES    || 'GF - ' ||
                rec_desem.GOLES_CONTRA || 'GC');
        END IF;
    END LOOP;

    -- ========== DETALLES ==========
    IF p_mostrar_detalles = 'S' THEN

        -- Goleadores
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('MÁXIMOS GOLEADORES:');
        DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');

        FOR rec_gol IN (
            SELECT ANIO, NOMBRE AS JUGADOR, GOLES
            FROM (
                SELECT
                    g.ANIO,
                    jp.NOMBRE,
                    g.GOLES,
                    ROW_NUMBER() OVER (PARTITION BY g.ANIO ORDER BY g.GOLES DESC) AS RN
                FROM GOLEADOR g
                JOIN JUGADOR_PAIS jp ON g.ID_JUGADOR = jp.ID_JUGADOR
                WHERE g.ID_SELECCION = p_id_seleccion
                AND (p_anio IS NULL OR g.ANIO = p_anio)
            )
            WHERE RN <= 3
            ORDER BY ANIO DESC
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('  ' || rec_gol.ANIO || ': ' ||
                RPAD(rec_gol.JUGADOR, 25) || ' - ' || rec_gol.GOLES || ' goles');
        END LOOP;

        -- Tarjetas
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('TARJETAS DISCIPLINARIAS:');
        DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');

        FOR rec_tarjeta IN (
            SELECT
                ANIO,
                SUM(AMARILLAS) AS AMARILLAS,
                SUM(ROJAS)     AS ROJAS
            FROM TARJETA
            WHERE ID_SELECCION = p_id_seleccion
            AND (p_anio IS NULL OR ANIO = p_anio)
            GROUP BY ANIO
            ORDER BY ANIO DESC
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('  ' || rec_tarjeta.ANIO || ': ' ||
                rec_tarjeta.AMARILLAS || ' amarillas | ' ||
                rec_tarjeta.ROJAS     || ' rojas');
        END LOOP;

        -- Detalle jugadores
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('DETALLE DE JUGADORES:');
        DBMS_OUTPUT.PUT_LINE('────────────────────────────────────────────────────────────');

        FOR rec_jug IN (
            SELECT
                jp.NOMBRE,
                dj.ANIO,
                dj.POSICION,
                dj.CAMISETA,
                dj.JUGO,
                dj.JUGO_TITULAR,
                dj.GOLES,
                dj.TARJETA_AMARILLA,
                dj.TARJETA_ROJA
            FROM DETALLE_JUGADOR dj
            JOIN JUGADOR_PAIS jp ON dj.ID_JUGADOR = jp.ID_JUGADOR
            WHERE jp.ID_SELECCION = p_id_seleccion
            AND (p_anio IS NULL OR dj.ANIO = p_anio)
            ORDER BY dj.ANIO DESC, dj.POSICION, jp.NOMBRE
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('  ' || rec_jug.ANIO || ' | ' ||
                RPAD(rec_jug.NOMBRE, 25)   || ' | ' ||
                RPAD(NVL(rec_jug.POSICION, '-'), 12) || ' | ' ||
                'Camiseta: ' || NVL(TO_CHAR(rec_jug.CAMISETA), '-') || ' | ' ||
                'Partidos: ' || NVL(TO_CHAR(rec_jug.JUGO), '0')     || ' | ' ||
                'Goles: '    || NVL(TO_CHAR(rec_jug.GOLES), '0')    || ' | ' ||
                'TA: ' || NVL(TO_CHAR(rec_jug.TARJETA_AMARILLA), '0') ||
                ' TR: ' || NVL(TO_CHAR(rec_jug.TARJETA_ROJA), '0'));
        END LOOP;

    END IF;

    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════════════════════');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: País con ID ' || p_id_seleccion || ' no encontrado.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END sp_info_pais;


/
--------------------------------------------------------
--  Constraints for Table LOG_GRUPO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_GRUPO" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSICION_FINAL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."POSICION_FINAL" MODIFY ("ID_POSICION_FINAL" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."POSICION_FINAL" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."POSICION_FINAL" MODIFY ("POSICION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."POSICION_FINAL" MODIFY ("ID_SELECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."POSICION_FINAL" ADD CONSTRAINT "PK_POSICION_FINAL" PRIMARY KEY ("ID_POSICION_FINAL")
  USING INDEX "PROYECTO2BASES2"."PK_POSICION_FINAL"  ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."POSICION_FINAL" ADD CONSTRAINT "UQ_POSFIN_POSICION" UNIQUE ("ANIO", "POSICION")
  USING INDEX "PROYECTO2BASES2"."UQ_POSFIN_POSICION"  ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."POSICION_FINAL" ADD CONSTRAINT "UQ_POSFIN_SELECCION" UNIQUE ("ANIO", "ID_SELECCION")
  USING INDEX "PROYECTO2BASES2"."UQ_POSFIN_SELECCION"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MUNDIAL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."MUNDIAL" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."MUNDIAL" ADD CONSTRAINT "PK_MUNDIAL" PRIMARY KEY ("ANIO")
  USING INDEX "PROYECTO2BASES2"."PK_MUNDIAL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARTIDO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."PARTIDO" MODIFY ("ID_PARTIDO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."PARTIDO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."PARTIDO" MODIFY ("NUM_PARTIDO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."PARTIDO" ADD CONSTRAINT "PK_PARTIDO" PRIMARY KEY ("ID_PARTIDO")
  USING INDEX "PROYECTO2BASES2"."PK_PARTIDO"  ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."PARTIDO" ADD CONSTRAINT "UQ_PARTIDO" UNIQUE ("ANIO", "NUM_PARTIDO")
  USING INDEX "PROYECTO2BASES2"."UQ_PARTIDO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_JUGADOR
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."DETALLE_JUGADOR" MODIFY ("ID_JUGADOR" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."DETALLE_JUGADOR" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."DETALLE_JUGADOR" ADD CONSTRAINT "PK_DETALLE_JUGADOR" PRIMARY KEY ("ID_JUGADOR", "ANIO")
  USING INDEX "PROYECTO2BASES2"."PK_DETALLE_JUGADOR"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_POSICION_GRUPO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_POSICION_GRUPO" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TARJETA
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."TARJETA" MODIFY ("ID_TARJETA" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."TARJETA" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."TARJETA" MODIFY ("ID_JUGADOR" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."TARJETA" MODIFY ("ID_SELECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."TARJETA" ADD CONSTRAINT "PK_TARJETA" PRIMARY KEY ("ID_TARJETA")
  USING INDEX "PROYECTO2BASES2"."PK_TARJETA"  ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."TARJETA" ADD CONSTRAINT "UQ_TARJETA" UNIQUE ("ANIO", "ID_JUGADOR")
  USING INDEX "PROYECTO2BASES2"."UQ_TARJETA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREMIO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."PREMIO" MODIFY ("ID_PREMIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."PREMIO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."PREMIO" MODIFY ("ID_TIPO_PREMIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."PREMIO" MODIFY ("ID_SELECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."PREMIO" ADD CONSTRAINT "PK_PREMIO" PRIMARY KEY ("ID_PREMIO")
  USING INDEX "PROYECTO2BASES2"."PK_PREMIO"  ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."PREMIO" ADD CONSTRAINT "UQ_PREMIO" UNIQUE ("ANIO", "ID_TIPO_PREMIO")
  USING INDEX "PROYECTO2BASES2"."UQ_PREMIO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPO_IDEAL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" MODIFY ("ID_EQUIPO_IDEAL" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" MODIFY ("POSICION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" MODIFY ("ID_JUGADOR" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" MODIFY ("ID_SELECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" ADD CONSTRAINT "PK_EQUIPO_IDEAL" PRIMARY KEY ("ID_EQUIPO_IDEAL")
  USING INDEX "PROYECTO2BASES2"."PK_EQUIPO_IDEAL"  ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" ADD CONSTRAINT "UQ_EQIDEAL_JUG" UNIQUE ("ANIO", "ID_JUGADOR")
  USING INDEX "PROYECTO2BASES2"."UQ_EQIDEAL_JUG"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."GRUPO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."GRUPO" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."GRUPO" ADD CONSTRAINT "PK_GRUPO" PRIMARY KEY ("ANIO", "ID_GRUPO")
  USING INDEX "PROYECTO2BASES2"."PK_GRUPO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_PREMIO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_PREMIO" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_TIPO_PREMIO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_TIPO_PREMIO" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_POSICION_FINAL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_POSICION_FINAL" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GOL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."GOL" MODIFY ("ID_GOL" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."GOL" MODIFY ("ID_PARTIDO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."GOL" MODIFY ("ID_SELECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."GOL" MODIFY ("MINUTO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."GOL" ADD CONSTRAINT "PK_GOL" PRIMARY KEY ("ID_GOL")
  USING INDEX "PROYECTO2BASES2"."PK_GOL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_EQUIPO_IDEAL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_EQUIPO_IDEAL" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_SELECCION
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_SELECCION" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSICION_GRUPO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."POSICION_GRUPO" MODIFY ("ID_POSICION_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."POSICION_GRUPO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."POSICION_GRUPO" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."POSICION_GRUPO" MODIFY ("ID_SELECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."POSICION_GRUPO" ADD CONSTRAINT "PK_POSICION_GRUPO" PRIMARY KEY ("ID_POSICION_GRUPO")
  USING INDEX "PROYECTO2BASES2"."PK_POSICION_GRUPO"  ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."POSICION_GRUPO" ADD CONSTRAINT "UQ_POSICION" UNIQUE ("ANIO", "ID_GRUPO", "ID_SELECCION")
  USING INDEX "PROYECTO2BASES2"."UQ_POSICION"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_JUGADOR_PAIS
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_JUGADOR_PAIS" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_PREMIO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."TIPO_PREMIO" MODIFY ("ID_TIPO_PREMIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."TIPO_PREMIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."TIPO_PREMIO" ADD CONSTRAINT "PK_TIPO_PREMIO" PRIMARY KEY ("ID_TIPO_PREMIO")
  USING INDEX "PROYECTO2BASES2"."PK_TIPO_PREMIO"  ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."TIPO_PREMIO" ADD CONSTRAINT "UQ_TIPO_PREMIO" UNIQUE ("NOMBRE")
  USING INDEX "PROYECTO2BASES2"."UQ_TIPO_PREMIO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_MUNDIAL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_MUNDIAL" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SELECCION
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."SELECCION" MODIFY ("ID_SELECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."SELECCION" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."SELECCION" ADD CONSTRAINT "PK_SELECCION" PRIMARY KEY ("ID_SELECCION")
  USING INDEX "PROYECTO2BASES2"."PK_SELECCION"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_PARTIDO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_PARTIDO" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GOLEADOR
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."GOLEADOR" MODIFY ("ID_GOLEADOR" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."GOLEADOR" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."GOLEADOR" MODIFY ("ID_SELECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."GOLEADOR" ADD CONSTRAINT "PK_GOLEADOR" PRIMARY KEY ("ID_GOLEADOR")
  USING INDEX "PROYECTO2BASES2"."PK_GOLEADOR"  ENABLE;

-- ========================================================
-- FASE 4: AGREGAR CONSTRAINTS (INTEGRIDAD)
-- Defines relaciones entre tablas con claves primarias 
-- y extranjeras (FOREIGN KEY) para mantener integridad
-- ========================================================
--------------------------------------------------------
--  Constraints for Table LOG_DETALLE_JUGADOR
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_DETALLE_JUGADOR" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_GOL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_GOL" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_TARJETA
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_TARJETA" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JUGADOR_PAIS
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."JUGADOR_PAIS" MODIFY ("ID_JUGADOR" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."JUGADOR_PAIS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."JUGADOR_PAIS" MODIFY ("ID_SELECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO2BASES2"."JUGADOR_PAIS" ADD CONSTRAINT "PK_JUGADOR_PAIS" PRIMARY KEY ("ID_JUGADOR")
  USING INDEX "PROYECTO2BASES2"."PK_JUGADOR_PAIS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_GOLEADOR
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."LOG_GOLEADOR" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_JUGADOR
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."DETALLE_JUGADOR" ADD CONSTRAINT "FK_DETALLE_JUGADOR_JUG" FOREIGN KEY ("ID_JUGADOR")
	  REFERENCES "PROYECTO2BASES2"."JUGADOR_PAIS" ("ID_JUGADOR") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."DETALLE_JUGADOR" ADD CONSTRAINT "FK_DETALLE_JUGADOR_MUN" FOREIGN KEY ("ANIO")
	  REFERENCES "PROYECTO2BASES2"."MUNDIAL" ("ANIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPO_IDEAL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" ADD CONSTRAINT "FK_EQIDEAL_MUN" FOREIGN KEY ("ANIO")
	  REFERENCES "PROYECTO2BASES2"."MUNDIAL" ("ANIO") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" ADD CONSTRAINT "FK_EQIDEAL_JUG" FOREIGN KEY ("ID_JUGADOR")
	  REFERENCES "PROYECTO2BASES2"."JUGADOR_PAIS" ("ID_JUGADOR") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."EQUIPO_IDEAL" ADD CONSTRAINT "FK_EQIDEAL_SEL" FOREIGN KEY ("ID_SELECCION")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."GOL" ADD CONSTRAINT "FK_GOL_PARTIDO" FOREIGN KEY ("ID_PARTIDO")
	  REFERENCES "PROYECTO2BASES2"."PARTIDO" ("ID_PARTIDO") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."GOL" ADD CONSTRAINT "FK_GOL_SEL" FOREIGN KEY ("ID_SELECCION")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."GOL" ADD CONSTRAINT "FK_GOL_JUG" FOREIGN KEY ("ID_JUGADOR")
	  REFERENCES "PROYECTO2BASES2"."JUGADOR_PAIS" ("ID_JUGADOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOLEADOR
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."GOLEADOR" ADD CONSTRAINT "FK_GOLEADOR_SEL" FOREIGN KEY ("ID_SELECCION")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."GOLEADOR" ADD CONSTRAINT "FK_GOLEADOR_JUG" FOREIGN KEY ("ID_JUGADOR")
	  REFERENCES "PROYECTO2BASES2"."JUGADOR_PAIS" ("ID_JUGADOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."GRUPO" ADD CONSTRAINT "FK_GRUPO_MUN" FOREIGN KEY ("ANIO")
	  REFERENCES "PROYECTO2BASES2"."MUNDIAL" ("ANIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUGADOR_PAIS
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."JUGADOR_PAIS" ADD CONSTRAINT "FK_JUGADOR_SEL" FOREIGN KEY ("ID_SELECCION")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUNDIAL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."MUNDIAL" ADD CONSTRAINT "FK_MUN_ORG" FOREIGN KEY ("ID_ORGANIZADOR")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."MUNDIAL" ADD CONSTRAINT "FK_MUN_CAMPEON" FOREIGN KEY ("ID_CAMPEON")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTIDO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."PARTIDO" ADD CONSTRAINT "FK_PARTIDO_MUN" FOREIGN KEY ("ANIO")
	  REFERENCES "PROYECTO2BASES2"."MUNDIAL" ("ANIO") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."PARTIDO" ADD CONSTRAINT "FK_PARTIDO_LOCAL" FOREIGN KEY ("ID_LOCAL")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."PARTIDO" ADD CONSTRAINT "FK_PARTIDO_VISIT" FOREIGN KEY ("ID_VISITANTE")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POSICION_FINAL
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."POSICION_FINAL" ADD CONSTRAINT "FK_POSFIN_MUN" FOREIGN KEY ("ANIO")
	  REFERENCES "PROYECTO2BASES2"."MUNDIAL" ("ANIO") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."POSICION_FINAL" ADD CONSTRAINT "FK_POSFIN_SEL" FOREIGN KEY ("ID_SELECCION")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POSICION_GRUPO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."POSICION_GRUPO" ADD CONSTRAINT "FK_POSGRP_GRUPO" FOREIGN KEY ("ANIO", "ID_GRUPO")
	  REFERENCES "PROYECTO2BASES2"."GRUPO" ("ANIO", "ID_GRUPO") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."POSICION_GRUPO" ADD CONSTRAINT "FK_POSGRP_SEL" FOREIGN KEY ("ID_SELECCION")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREMIO
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."PREMIO" ADD CONSTRAINT "FK_PREMIO_MUN" FOREIGN KEY ("ANIO")
	  REFERENCES "PROYECTO2BASES2"."MUNDIAL" ("ANIO") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."PREMIO" ADD CONSTRAINT "FK_PREMIO_TIPO" FOREIGN KEY ("ID_TIPO_PREMIO")
	  REFERENCES "PROYECTO2BASES2"."TIPO_PREMIO" ("ID_TIPO_PREMIO") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."PREMIO" ADD CONSTRAINT "FK_PREMIO_SEL" FOREIGN KEY ("ID_SELECCION")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."PREMIO" ADD CONSTRAINT "FK_PREMIO_JUG" FOREIGN KEY ("ID_JUGADOR")
	  REFERENCES "PROYECTO2BASES2"."JUGADOR_PAIS" ("ID_JUGADOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TARJETA
--------------------------------------------------------

  ALTER TABLE "PROYECTO2BASES2"."TARJETA" ADD CONSTRAINT "FK_TARJETA_MUN" FOREIGN KEY ("ANIO")
	  REFERENCES "PROYECTO2BASES2"."MUNDIAL" ("ANIO") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."TARJETA" ADD CONSTRAINT "FK_TARJETA_JUG" FOREIGN KEY ("ID_JUGADOR")
	  REFERENCES "PROYECTO2BASES2"."JUGADOR_PAIS" ("ID_JUGADOR") ENABLE;
  ALTER TABLE "PROYECTO2BASES2"."TARJETA" ADD CONSTRAINT "FK_TARJETA_SEL" FOREIGN KEY ("ID_SELECCION")
	  REFERENCES "PROYECTO2BASES2"."SELECCION" ("ID_SELECCION") ENABLE;

