-- ============================================================
-- TRUNCAR TABLAS PARA PRUEBA DE RESTAURACION
-- Orden correcto: tablas hijo (con FK) primero, luego tablas padre
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

BEGIN
    DBMS_OUTPUT.PUT_LINE('INICIANDO TRUNCATE DE TABLAS...');
    DBMS_OUTPUT.PUT_LINE('Timestamp: ' || TO_CHAR(SYSTIMESTAMP, 'DD/MM/YYYY HH24:MI:SS'));
END;
/

-- TRUNCAR TABLAS (vaciarlas) - Orden: tablas hijo primero
-- Tablas con ForeignKey (HIJO)
TRUNCATE TABLE GOL;
TRUNCATE TABLE TARJETA;
TRUNCATE TABLE GOLEADOR;
TRUNCATE TABLE EQUIPO_IDEAL;
TRUNCATE TABLE PREMIO;
TRUNCATE TABLE POSICION_GRUPO;
TRUNCATE TABLE POSICION_FINAL;
TRUNCATE TABLE JUGADOR_PAIS;
TRUNCATE TABLE DETALLE_JUGADOR;
TRUNCATE TABLE PARTIDO;
TRUNCATE TABLE GRUPO;
TRUNCATE TABLE TIPO_PREMIO;

-- Tablas PADRE (sin FK a otras tablas)
TRUNCATE TABLE SELECCION;
TRUNCATE TABLE MUNDIAL;

COMMIT;

BEGIN
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('=== TABLAS TRUNCADAS EXITOSAMENTE ===');
    DBMS_OUTPUT.PUT_LINE('Timestamp: ' || TO_CHAR(SYSTIMESTAMP, 'DD/MM/YYYY HH24:MI:SS'));
    DBMS_OUTPUT.PUT_LINE('Las tablas estan vacias. Ahora ejecuta RMAN RESTORE.');
END;
/

-- VERIFICAR QUE ESTEN VACIAS
SELECT 'MUNDIAL' AS TABLA, COUNT(*) FROM MUNDIAL
UNION ALL SELECT 'SELECCION', COUNT(*) FROM SELECCION
UNION ALL SELECT 'PARTIDO', COUNT(*) FROM PARTIDO
UNION ALL SELECT 'GOL', COUNT(*) FROM GOL
UNION ALL SELECT 'GRUPO', COUNT(*) FROM GRUPO
UNION ALL SELECT 'GOLEADOR', COUNT(*) FROM GOLEADOR;
